library(tidyverse)

# Read the messy department names into a vector
indata <- tibble(read.csv("salary.csv"))
dept_names <- unique(indata$department)

# trim whitespace
dept_names <- trimws(dept_names)

# Create a data frame to store the original names
dept_df <- data.frame(Original = dept_names, stringsAsFactors = FALSE)

# Define the mapping function
map_dept_name <- function(name) {
  name_lower <- tolower(name)
  
  # Define patterns and standardized names
  patterns <- c(
    "mechanical eng|mecheng|mech eng|mech\\.\\?$",
    "electrical|ece|electrical & computer eng|electrical and comp|comput",
    "civil eng|civil & mech eng|cme|civil engineering",
    "computer science|comp sci",
    "chemistry|chem eng|chemical eng|chemistry and physi|chemical engineering",
    "physics|phys & astr|physics and astronom|phys",
    "mathematics|math, stat|math|mathematics",
    "biology|bio sci|biological sciences|biological science|dept of biolo",
    "business|school of mgmt|management|school of management|managerial",
    "nursing",
    "psychology|psychological scienc",
    "sociology",
    "anthropology",
    "history",
    "philosophy",
    "library|university library",
    "registrar",
    "admissions",
    "financial aid",
    "bursar",
    "student life|student services|dean of students|student activit|student developm|student athletics|student success",
    "police|public safety|university police",
    "fire department|fire dept",
    "human resources|hr",
    "career services",
    "counseling center",
    "international|international progr",
    "graduate school|graduate studies",
    "athletics|athletic",
    "marketing",
    "communication|communications|communication and c",
    "english|english and philoso",
    "foreign languages|dept of foreign lan|international langua",
    "engineering|engineering technol|engineering & techno",
    "agricultural|agriculture|agronomy|agricultural economi",
    "economics",
    "finance",
    "accounting",
    "biochemistry",
    "statistics",
    "veterinary|vet",
    "music",
    "theater|theatre",
    "art|fine arts",
    "pharmacy|pharmaceutical",
    "biomedical|biomedical engineeri",
    "environmental|environmental & ecol",
    "health sciences|health & human servi|health and human services",
    "housing|residence hall|residence life|residence housing|housing and residen",
    "dining|food services|foodservice|dining services|purdue dine",
    "maintenance|operations & maintenance|physical facilities|building services|facilities",
    "botany",
    "entomology",
    "geosciences|earth sciences|eaps",
    "graduate studies",
    "computer graphics",
    "information technology|it|information technolo|it networks & securi|comp inf|it|information technology|computer informatio|computer technology|information service|administrative computing|information technology|enterprise systems|enterprise applications|it customer relation",
    "speech|language|hearing|speech, language and",
    "materials science|materials engineerin",
    "civil engineering",
    "chemical engineering",
    "aerospace engineering|aeronautics & astron",
    "industrial engineering|industrial and physi",
    "nuclear engineering",
    "political science",
    "social sciences|social science",
    "human development",
    "consumer sciences",
    "kinesiology|health & kinesio|health and kinesio",
    "art & design|visual & performing|fine arts|art&des|visual communication",
    "interdisciplinary",
    "student housing|housing and food ser|housing and residen",
    "student activities|student life|student services|student counseling|student success",
    "institutional research|institutional resear",
    "purchasing|procurement|stores & service|general stores|purchasing and gene",
    "payroll|budgets|budget office|accounting services|accounts payable",
    "facilities and maintenance|physical facilities|building services|maintenance|grounds|utilities|energy management|operations & maintenance|physical plant|building systems|facility engineering",
    "research|sponsored program services|sps|office of research|vice president for research|discovery park",
    "development|advancement|alumni relations|university relations|office of marketing",
    "environmental sciences|climate change|environmental & ecol",
    "women's studies|women in engineering",
    "student health center|health services|push|student health cent",
    "university press",
    "marketing and communications|publications|marketing promotions|marketing, publicati",
    "conference services|convocations|conference division|calumet conference",
    "legal|office of legal counsel",
    "president|chancellor|vice president|vice chancellor|vice provost|provost|office of the provos",
    "finance|budget|accounting",
    "health sciences|health and human sciences|medical education",
    "construction|construction scienc|bldg construction ma",
    "student housing|residence hall|residence life|residence housing|housing and residen|university residence"
  )
  
  replacements <- c(
    "Mechanical Engineering",
    "Electrical and Computer Engineering",
    "Civil Engineering",
    "Computer Science",
    "Chemistry",
    "Physics",
    "Mathematics",
    "Biology",
    "School of Management",
    "Nursing",
    "Psychology",
    "Sociology",
    "Anthropology",
    "History",
    "Philosophy",
    "Library",
    "Registrar",
    "Admissions",
    "Financial Aid",
    "Bursar",
    "Student Services",
    "Police Department",
    "Fire Department",
    "Human Resources",
    "Career Services",
    "Counseling Center",
    "International Programs",
    "Graduate School",
    "Athletics",
    "Marketing",
    "Communication",
    "English",
    "Foreign Languages",
    "Engineering",
    "Agriculture",
    "Economics",
    "Finance",
    "Accounting",
    "Biochemistry",
    "Statistics",
    "Veterinary Medicine",
    "Music",
    "Theater",
    "Art",
    "Pharmacy",
    "Biomedical Engineering",
    "Environmental Sciences",
    "Health and Human Sciences",
    "Housing and Residence Life",
    "Dining Services",
    "Facilities and Maintenance",
    "Botany",
    "Entomology",
    "Earth, Atmospheric, and Planetary Sciences",
    "Graduate Studies",
    "Computer Graphics Technology",
    "Information Technology",
    "Speech, Language, and Hearing Sciences",
    "Materials Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Industrial Engineering",
    "Nuclear Engineering",
    "Political Science",
    "Social Sciences",
    "Human Development",
    "Consumer Sciences",
    "Health and Kinesiology",
    "Art and Design",
    "Interdisciplinary Studies",
    "Housing and Residence Life",
    "Student Services",
    "Institutional Research",
    "Procurement Services",
    "Financial Services",
    "Facilities and Maintenance",
    "Research",
    "Development and Alumni Relations",
    "Environmental Sciences",
    "Women's Studies",
    "Student Health Services",
    "University Press",
    "Marketing and Communications",
    "Conference Services",
    "Legal Counsel",
    "Administration",
    "Financial Services",
    "Health and Human Sciences",
    "Construction",
    "Housing and Residence Life"
  )
  
  # Iterate over patterns to find a match
  for (i in seq_along(patterns)) {
    if (str_detect(name_lower, patterns[i])) {
      return(replacements[i])
    }
  }
  
  # If no pattern matches, return the original name
  return(name)
}

# Apply the function to the department names
dept_df$Standardized <- sapply(dept_df$Original, map_dept_name)

# Next use a join to populate a new column
